-- EC-05: Orders + refunds + notes + state-transition log.
--
-- The order is the unit-of-record for fulfillment + accounting. It is created
-- by the checkout handler in `pending` and walks the state machine via
-- `backend/src/commerce/orders.rs::transition`:
--
--   pending → processing → on_hold? → completed → refunded?
--                                              ↘ cancelled
--                                              ↘ failed
--
-- Each transition writes a row to `order_state_transitions`; replays + audits
-- read from there. The webhook reconciler in `handlers::webhooks` is the
-- canonical source of `processing` → `completed` (driven by Stripe's
-- `payment_intent.succeeded`).
--
-- `number` is a human-friendly invoice id (`ORD-2026-00012345`) generated by
-- the service layer from a per-year sequence (the column is UNIQUE so the
-- DB enforces collision-freedom even if two replicas race).

CREATE TYPE order_status AS ENUM (
    'pending',
    'processing',
    'on_hold',
    'completed',
    'refunded',
    'cancelled',
    'failed'
);

CREATE TABLE IF NOT EXISTS orders (
    id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    number                   TEXT NOT NULL UNIQUE,
    user_id                  UUID REFERENCES users(id) ON DELETE SET NULL,
    cart_id                  UUID REFERENCES carts(id) ON DELETE SET NULL,
    status                   order_status NOT NULL DEFAULT 'pending',
    currency                 TEXT NOT NULL DEFAULT 'usd',
    subtotal_cents           BIGINT NOT NULL CHECK (subtotal_cents >= 0),
    discount_cents           BIGINT NOT NULL DEFAULT 0 CHECK (discount_cents >= 0),
    tax_cents                BIGINT NOT NULL DEFAULT 0 CHECK (tax_cents >= 0),
    total_cents              BIGINT NOT NULL CHECK (total_cents >= 0),
    email                    TEXT NOT NULL,
    stripe_payment_intent_id TEXT,
    stripe_customer_id       TEXT,
    idempotency_key          TEXT UNIQUE,
    metadata                 JSONB NOT NULL DEFAULT '{}',
    placed_at                TIMESTAMPTZ,
    completed_at             TIMESTAMPTZ,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS orders_user_id_idx ON orders (user_id);
CREATE INDEX IF NOT EXISTS orders_status_idx  ON orders (status);
CREATE INDEX IF NOT EXISTS orders_email_idx   ON orders (lower(email));
CREATE INDEX IF NOT EXISTS orders_stripe_pi_idx ON orders (stripe_payment_intent_id)
    WHERE stripe_payment_intent_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS order_items (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id            UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id          UUID NOT NULL REFERENCES products(id),
    variant_id          UUID REFERENCES product_variants(id),
    sku                 TEXT,
    name                TEXT NOT NULL,
    quantity            INT NOT NULL CHECK (quantity > 0),
    unit_price_cents    BIGINT NOT NULL CHECK (unit_price_cents >= 0),
    line_total_cents    BIGINT NOT NULL CHECK (line_total_cents >= 0),
    metadata            JSONB NOT NULL DEFAULT '{}',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS order_items_order_id_idx ON order_items (order_id);
CREATE INDEX IF NOT EXISTS order_items_product_id_idx ON order_items (product_id);

CREATE TABLE IF NOT EXISTS order_notes (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id    UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    author_id   UUID REFERENCES users(id) ON DELETE SET NULL,
    kind        TEXT NOT NULL CHECK (kind IN ('customer','internal')),
    body        TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS order_notes_order_id_idx ON order_notes (order_id);

CREATE TABLE IF NOT EXISTS order_refunds (
    id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id           UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    amount_cents       BIGINT NOT NULL CHECK (amount_cents > 0),
    reason             TEXT,
    stripe_refund_id   TEXT UNIQUE,
    created_by         UUID REFERENCES users(id) ON DELETE SET NULL,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS order_refunds_order_id_idx ON order_refunds (order_id);

CREATE TABLE IF NOT EXISTS order_state_transitions (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id    UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    from_status order_status NOT NULL,
    to_status   order_status NOT NULL,
    actor_id    UUID REFERENCES users(id) ON DELETE SET NULL,
    reason      TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS order_state_transitions_order_id_idx
    ON order_state_transitions (order_id);

-- Per-year sequence used by the service layer to mint `ORD-YYYY-NNNNNNNN`
-- numbers without a hot-path scan. Recreated each January via cron — for
-- the migration we just stand up the 2026 sequence so the first order
-- doesn't bootstrap-fail.
CREATE SEQUENCE IF NOT EXISTS orders_number_seq_2026
    INCREMENT 1 START 1 CACHE 50;
