#!/usr/bin/env node
/**
 * FDN-02: Generate `src/lib/api/schema.d.ts` from the committed OpenAPI snapshot
 * (`backend/tests/snapshots/openapi.json`). Runs on `pnpm gen:types`, which is
 * prepended to `pnpm check` and `pnpm ci:frontend`.
 *
 * Programmatic use only — importing `openapi-typescript` as a library avoids
 * shelling out to its CLI and keeps the script deterministic across platforms.
 */

import { mkdir, readFile, stat, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Dynamic import so the script can be called in contexts where
 * `openapi-typescript` is not yet installed (e.g., initial repo clone).
 * In that case we leave any committed `schema.d.ts` untouched and warn —
 * the type check can still pass off the committed baseline.
 */
let openapiTS;
let astToString;
try {
	const mod = await import('openapi-typescript');
	openapiTS = mod.default;
	astToString = mod.astToString;
} catch (err) {
	if (err && (err.code === 'ERR_MODULE_NOT_FOUND' || err.code === 'MODULE_NOT_FOUND')) {
		console.warn(
			'[openapi-to-ts] openapi-typescript not installed; skipping codegen. Run `pnpm install` first.'
		);
		process.exit(0);
	}
	throw err;
}

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..');

const snapshotPath = resolve(repoRoot, 'backend/tests/snapshots/openapi.json');
const outPath = resolve(repoRoot, 'src/lib/api/schema.d.ts');

const banner = `/**
 * AUTO-GENERATED by scripts/openapi-to-ts.mjs from backend/tests/snapshots/openapi.json.
 * Do not edit by hand. Regenerate with: pnpm gen:types
 *
 * Source of truth: Rust #[utoipa::path(...)] annotations in backend/src/handlers/*.rs.
 * To update the snapshot, run:
 *   UPDATE_OPENAPI_SNAPSHOT=1 cargo test --manifest-path backend/Cargo.toml --test openapi_snapshot
 */
`;

async function main() {
	// Minor existence safety check to keep the error surface explicit.
	await stat(snapshotPath).catch(() => null);

	let raw;
	try {
		raw = await readFile(snapshotPath, 'utf8');
	} catch (err) {
		if (err && err.code === 'ENOENT') {
			console.error(
				`[openapi-to-ts] snapshot missing at ${snapshotPath}. Run the backend tests first:\n` +
					`  UPDATE_OPENAPI_SNAPSHOT=1 cargo test --manifest-path backend/Cargo.toml --test openapi_snapshot`
			);
			process.exit(1);
		}
		throw err;
	}

	// Validate the JSON up-front so malformed snapshots fail fast with a clear error.
	JSON.parse(raw);

	const ast = await openapiTS(new URL(`file://${snapshotPath}`), {
		exportType: true,
		immutable: false
	});

	const generated = astToString(ast);
	const out = `${banner}\n${generated}`;

	await mkdir(dirname(outPath), { recursive: true });
	await writeFile(outPath, out, 'utf8');

	console.log(`[openapi-to-ts] wrote ${outPath} (${out.length} bytes)`);
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
